# Generated by Django 4.1.5 on 2023-01-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=100)),
                ("document_type", models.CharField(max_length=20)),
                ("theme", models.CharField(max_length=50)),
                ("made_by", models.CharField(max_length=50)),
                ("signed_by", models.CharField(max_length=50)),
                ("date_of_manufacture", models.DateField()),
            ],
        ),
    ]
