# Generated by Django 4.1.5 on 2023-01-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="<django.db.models.query_utils.DeferredAttribute object at 0x000002080CDA8790>.jpg",
                upload_to="media",
            ),
        ),
    ]
